// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7DvVJwTWM8In3zD6e0vgkrrkVqcoRyU',
    appId: '1:711008496705:web:626c26576bedfe5767eac0',
    messagingSenderId: '711008496705',
    projectId: 'authentication-task-c0edd',
    authDomain: 'authentication-task-c0edd.firebaseapp.com',
    storageBucket: 'authentication-task-c0edd.firebasestorage.app',
    measurementId: 'G-P09P83EEQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArLxpFyTzQ0a4HKEnWKDk1VV_zOsmgIjU',
    appId: '1:711008496705:android:047622032ee0724667eac0',
    messagingSenderId: '711008496705',
    projectId: 'authentication-task-c0edd',
    storageBucket: 'authentication-task-c0edd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiHxP0mAaDn5icDWeQ_78j5OL8sDCVqKM',
    appId: '1:711008496705:ios:f309de1850636ff167eac0',
    messagingSenderId: '711008496705',
    projectId: 'authentication-task-c0edd',
    storageBucket: 'authentication-task-c0edd.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiHxP0mAaDn5icDWeQ_78j5OL8sDCVqKM',
    appId: '1:711008496705:ios:f309de1850636ff167eac0',
    messagingSenderId: '711008496705',
    projectId: 'authentication-task-c0edd',
    storageBucket: 'authentication-task-c0edd.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7DvVJwTWM8In3zD6e0vgkrrkVqcoRyU',
    appId: '1:711008496705:web:6bb4d8c2355857ca67eac0',
    messagingSenderId: '711008496705',
    projectId: 'authentication-task-c0edd',
    authDomain: 'authentication-task-c0edd.firebaseapp.com',
    storageBucket: 'authentication-task-c0edd.firebasestorage.app',
    measurementId: 'G-1RDTRLF2XK',
  );
}
